(async()=>{await new Promise(r=>setTimeout(r,2600));
const lum=c=>{const m=c.match(/[\d.]+/g);if(!m)return null;const [r,g,b,a]=m.map(Number);if(a!==undefined&&a<.5)return null;const f=v=>{v/=255;return v<=.03928?v/12.92:Math.pow((v+.055)/1.055,2.4)};return .2126*f(r)+.7152*f(g)+.0722*f(b)};
const H=document.documentElement;const prev=H.getAttribute('data-theme');H.setAttribute('data-theme','dark');await new Promise(r=>setTimeout(r,250));
const light=[],darkTxt=[];document.querySelectorAll('main *, header *, aside *').forEach(e=>{const cs=getComputedStyle(e);if(cs.display==='none'||cs.visibility==='hidden')return;const r=e.getBoundingClientRect();if(!r.width||!r.height)return;const bg=cs.backgroundColor;const L=lum(bg);if(L!==null&&L>.6&&r.width>24&&r.height>16)light.push(e.tagName+'.'+(e.className&&e.className.baseVal===undefined?e.className:'')+'|'+(e.textContent||'').trim().slice(0,18)+'|'+bg);
if(e.childNodes.length&&[...e.childNodes].some(n=>n.nodeType===3&&n.textContent.trim())){const tl=lum(cs.color);if(tl!==null&&tl<.08)darkTxt.push((e.textContent||'').trim().slice(0,18)+'|'+cs.color);}});
H.setAttribute('data-theme',prev||'light');
const out={light:[...new Set(light)].slice(0,8),darkTxt:[...new Set(darkTxt)].slice(0,8)};
for(const W of [1024,768,390]){let flat='';for(const sh of document.styleSheets){let rs;try{rs=sh.cssRules}catch(e){continue}for(const r of rs){const t=r.conditionText||(r.media&&r.media.mediaText)||'';const mx=t.match(/max-width:\s*(\d+)px/),mn=t.match(/min-width:\s*(\d+)px/);if(mx&&+mx[1]>=W&&(!mn||+mn[1]<=W)){for(const c of r.cssRules)flat+=c.cssText+'\n';}}}const st=document.createElement('style');st.textContent='html,body{width:'+W+'px!important;max-width:'+W+'px!important;overflow-x:hidden}\n'+flat;document.head.appendChild(st);await new Promise(r=>setTimeout(r,300));
const off=[];document.querySelectorAll('body *').forEach(e=>{const cs=getComputedStyle(e);if(cs.position==='fixed'||cs.display==='none')return;const r=e.getBoundingClientRect();if(r.width>0&&r.height>0&&r.right>W+2){let a=e.parentElement,k=0,c=false;while(a&&a.tagName!=='BODY'&&k++<60){const o=getComputedStyle(a).overflowX;if((o==='auto'||o==='scroll'||o==='hidden')&&a.getBoundingClientRect().right<=W+2){c=true;break;}a=a.parentElement;}if(!c)off.push(e.tagName+'|'+(e.textContent||'').trim().slice(0,20)+'|r='+Math.round(r.right));}});
const hid=[];document.querySelectorAll('[style*="overflow-x:auto"],[style*="overflow-x: auto"]').forEach(e=>{if(e.scrollWidth>e.clientWidth+4&&e.closest('main'))hid.push((e.className||'')+' sw='+e.scrollWidth+'/'+e.clientWidth);});
const crowd=[];document.querySelectorAll('main b, main h1, main h2, main h3').forEach(e=>{if(e.scrollWidth>e.clientWidth+2&&getComputedStyle(e).overflow!=='visible')crowd.push(e.textContent.trim().slice(0,20));});
out[W]={off:[...new Set(off)].slice(0,5),hscroll:hid.slice(0,4),crowd:crowd.slice(0,4)};st.remove();}
return out;})()